from . import common
from . import start
from . import register
from . import appeal
from . import management
from . import send_file
from . import statistics
from . import cabinet
from . import about
from . import ariza
